apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-test-app
spec:
  rules:
    - host: devops-test-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-test-app
                port:
                  number: 3000
